apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAicmFsZWtoaW4iLAogICAgICAicGFzc3dvcmQiOiAiZ2hwX3NZWmxvQzh4czNXOHR3M0p4bFg0c1h4UlJGQ2dNYjQ4dnFrZCIsCiAgICAgICJzZXJ2ZXJhZGRyZXNzIjogImdoY3IuaW8iCiAgICB9CiAgfSwKICAiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKICAiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCiAgInBsdWdpbnMiOiB7CiAgICAiLXgtY2xpLWhpbnRzIjogewogICAgICAiZW5hYmxlZCI6ICJ0cnVlIgogICAgfQogIH0sCiAgImZlYXR1cmVzIjogewogICAgImhvb2tzIjogInRydWUiCiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
